server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    # Redirección para Ventas
    location /api/ventas {
        proxy_pass http://10.0.3.17:8082/api/v1/ventas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirección para Despachos
    location /api/despachos {
        proxy_pass http://10.0.3.17:8081/api/v1/despachos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}